// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: canciones.proto

package servicios_canciones

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Mensajes (DTOs) ---
type Genero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Genero) Reset() {
	*x = Genero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{0}
}

func (x *Genero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genero) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type Cancion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo          string  `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Artista         string  `protobuf:"bytes,3,opt,name=artista,proto3" json:"artista,omitempty"`
	AnioLanzamiento int32   `protobuf:"varint,4,opt,name=anio_lanzamiento,json=anioLanzamiento,proto3" json:"anio_lanzamiento,omitempty"`
	Duracion        string  `protobuf:"bytes,5,opt,name=duracion,proto3" json:"duracion,omitempty"`
	Genero          *Genero `protobuf:"bytes,6,opt,name=genero,proto3" json:"genero,omitempty"`
}

func (x *Cancion) Reset() {
	*x = Cancion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancion) ProtoMessage() {}

func (x *Cancion) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancion.ProtoReflect.Descriptor instead.
func (*Cancion) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{1}
}

func (x *Cancion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cancion) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Cancion) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

func (x *Cancion) GetAnioLanzamiento() int32 {
	if x != nil {
		return x.AnioLanzamiento
	}
	return 0
}

func (x *Cancion) GetDuracion() string {
	if x != nil {
		return x.Duracion
	}
	return ""
}

func (x *Cancion) GetGenero() *Genero {
	if x != nil {
		return x.Genero
	}
	return nil
}

// --- Mensajes de Petición/Respuesta ---
type GetGenerosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGenerosRequest) Reset() {
	*x = GetGenerosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenerosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerosRequest) ProtoMessage() {}

func (x *GetGenerosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerosRequest.ProtoReflect.Descriptor instead.
func (*GetGenerosRequest) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{2}
}

type GetGenerosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generos []*Genero `protobuf:"bytes,1,rep,name=generos,proto3" json:"generos,omitempty"`
}

func (x *GetGenerosResponse) Reset() {
	*x = GetGenerosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenerosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerosResponse) ProtoMessage() {}

func (x *GetGenerosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerosResponse.ProtoReflect.Descriptor instead.
func (*GetGenerosResponse) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{3}
}

func (x *GetGenerosResponse) GetGeneros() []*Genero {
	if x != nil {
		return x.Generos
	}
	return nil
}

type GetCancionesPorGeneroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdGenero int32 `protobuf:"varint,1,opt,name=id_genero,json=idGenero,proto3" json:"id_genero,omitempty"`
}

func (x *GetCancionesPorGeneroRequest) Reset() {
	*x = GetCancionesPorGeneroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCancionesPorGeneroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCancionesPorGeneroRequest) ProtoMessage() {}

func (x *GetCancionesPorGeneroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCancionesPorGeneroRequest.ProtoReflect.Descriptor instead.
func (*GetCancionesPorGeneroRequest) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{4}
}

func (x *GetCancionesPorGeneroRequest) GetIdGenero() int32 {
	if x != nil {
		return x.IdGenero
	}
	return 0
}

type GetCancionesPorGeneroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Canciones []*Cancion `protobuf:"bytes,1,rep,name=canciones,proto3" json:"canciones,omitempty"`
}

func (x *GetCancionesPorGeneroResponse) Reset() {
	*x = GetCancionesPorGeneroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCancionesPorGeneroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCancionesPorGeneroResponse) ProtoMessage() {}

func (x *GetCancionesPorGeneroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCancionesPorGeneroResponse.ProtoReflect.Descriptor instead.
func (*GetCancionesPorGeneroResponse) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{5}
}

func (x *GetCancionesPorGeneroResponse) GetCanciones() []*Cancion {
	if x != nil {
		return x.Canciones
	}
	return nil
}

type ConsultarCancionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCancion int32 `protobuf:"varint,1,opt,name=id_cancion,json=idCancion,proto3" json:"id_cancion,omitempty"`
}

func (x *ConsultarCancionRequest) Reset() {
	*x = ConsultarCancionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canciones_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultarCancionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarCancionRequest) ProtoMessage() {}

func (x *ConsultarCancionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_canciones_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarCancionRequest.ProtoReflect.Descriptor instead.
func (*ConsultarCancionRequest) Descriptor() ([]byte, []int) {
	return file_canciones_proto_rawDescGZIP(), []int{6}
}

func (x *ConsultarCancionRequest) GetIdCancion() int32 {
	if x != nil {
		return x.IdCancion
	}
	return 0
}

var File_canciones_proto protoreflect.FileDescriptor

var file_canciones_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e,
	0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x6e,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x6e, 0x69, 0x6f, 0x5f, 0x6c,
	0x61, 0x6e, 0x7a, 0x61, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x61, 0x6e, 0x69, 0x6f, 0x4c, 0x61, 0x6e, 0x7a, 0x61, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a,
	0x06, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69,
	0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x07, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x6f, 0x73, 0x22, 0x3b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x69,
	0x6f, 0x6e, 0x65, 0x73, 0x50, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x6f, 0x22, 0x5b, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65,
	0x73, 0x50, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f,
	0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x38,
	0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f,
	0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69,
	0x64, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x32, 0xd9, 0x02, 0x0a, 0x11, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x69, 0x6f, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x60,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73, 0x12,
	0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63,
	0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x81, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x69,
	0x6f, 0x6e, 0x65, 0x73, 0x50, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x12, 0x31, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73,
	0x50, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e,
	0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x50, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x72, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69,
	0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x69, 0x6f, 0x6e, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x69, 0x6f, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_canciones_proto_rawDescOnce sync.Once
	file_canciones_proto_rawDescData = file_canciones_proto_rawDesc
)

func file_canciones_proto_rawDescGZIP() []byte {
	file_canciones_proto_rawDescOnce.Do(func() {
		file_canciones_proto_rawDescData = protoimpl.X.CompressGZIP(file_canciones_proto_rawDescData)
	})
	return file_canciones_proto_rawDescData
}

var file_canciones_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_canciones_proto_goTypes = []interface{}{
	(*Genero)(nil),                        // 0: servicios_canciones.Genero
	(*Cancion)(nil),                       // 1: servicios_canciones.Cancion
	(*GetGenerosRequest)(nil),             // 2: servicios_canciones.GetGenerosRequest
	(*GetGenerosResponse)(nil),            // 3: servicios_canciones.GetGenerosResponse
	(*GetCancionesPorGeneroRequest)(nil),  // 4: servicios_canciones.GetCancionesPorGeneroRequest
	(*GetCancionesPorGeneroResponse)(nil), // 5: servicios_canciones.GetCancionesPorGeneroResponse
	(*ConsultarCancionRequest)(nil),       // 6: servicios_canciones.ConsultarCancionRequest
}
var file_canciones_proto_depIdxs = []int32{
	0, // 0: servicios_canciones.Cancion.genero:type_name -> servicios_canciones.Genero
	0, // 1: servicios_canciones.GetGenerosResponse.generos:type_name -> servicios_canciones.Genero
	1, // 2: servicios_canciones.GetCancionesPorGeneroResponse.canciones:type_name -> servicios_canciones.Cancion
	2, // 3: servicios_canciones.ServicioCanciones.ListarGeneros:input_type -> servicios_canciones.GetGenerosRequest
	4, // 4: servicios_canciones.ServicioCanciones.ListarCancionesPorGenero:input_type -> servicios_canciones.GetCancionesPorGeneroRequest
	6, // 5: servicios_canciones.ServicioCanciones.ConsultarCancion:input_type -> servicios_canciones.ConsultarCancionRequest
	3, // 6: servicios_canciones.ServicioCanciones.ListarGeneros:output_type -> servicios_canciones.GetGenerosResponse
	5, // 7: servicios_canciones.ServicioCanciones.ListarCancionesPorGenero:output_type -> servicios_canciones.GetCancionesPorGeneroResponse
	1, // 8: servicios_canciones.ServicioCanciones.ConsultarCancion:output_type -> servicios_canciones.Cancion
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_canciones_proto_init() }
func file_canciones_proto_init() {
	if File_canciones_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_canciones_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cancion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenerosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenerosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCancionesPorGeneroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCancionesPorGeneroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canciones_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultarCancionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canciones_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_canciones_proto_goTypes,
		DependencyIndexes: file_canciones_proto_depIdxs,
		MessageInfos:      file_canciones_proto_msgTypes,
	}.Build()
	File_canciones_proto = out.File
	file_canciones_proto_rawDesc = nil
	file_canciones_proto_goTypes = nil
	file_canciones_proto_depIdxs = nil
}
