// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: streaming.proto

package servicios_streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	// Método RPC para el streaming de la canción.
	// Recibe una petición y devuelve un 'stream' (flujo) de fragmentos.
	StreamAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (AudioService_StreamAudioClient, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) StreamAudio(ctx context.Context, in *PeticionDTO, opts ...grpc.CallOption) (AudioService_StreamAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], "/servicios_streaming.AudioService/StreamAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceStreamAudioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AudioService_StreamAudioClient interface {
	Recv() (*FragmentoCancion, error)
	grpc.ClientStream
}

type audioServiceStreamAudioClient struct {
	grpc.ClientStream
}

func (x *audioServiceStreamAudioClient) Recv() (*FragmentoCancion, error) {
	m := new(FragmentoCancion)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility
type AudioServiceServer interface {
	// Método RPC para el streaming de la canción.
	// Recibe una petición y devuelve un 'stream' (flujo) de fragmentos.
	StreamAudio(*PeticionDTO, AudioService_StreamAudioServer) error
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServiceServer struct {
}

func (UnimplementedAudioServiceServer) StreamAudio(*PeticionDTO, AudioService_StreamAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeticionDTO)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).StreamAudio(m, &audioServiceStreamAudioServer{stream})
}

type AudioService_StreamAudioServer interface {
	Send(*FragmentoCancion) error
	grpc.ServerStream
}

type audioServiceStreamAudioServer struct {
	grpc.ServerStream
}

func (x *audioServiceStreamAudioServer) Send(m *FragmentoCancion) error {
	return x.ServerStream.SendMsg(m)
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios_streaming.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _AudioService_StreamAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
